version: "3.5"

services:
  node-api:
    container_name: simple-web-app
    restart: always
    ports:
      - "3000:3000"
    image: simple-web-node-js
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm start"
    networks:
      - sw-network
  mongo-db:
    image: mongo:4.4
    container_name: simple-web-mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - sw-network
networks:
  sw-network:
    name: sw-network
    driver: bridge